### PR TITLE
Modified browser at api_wrapper.py

### PR DESCRIPTION
**Pull request by Infernite**
Made it so it appears as a phone rather than as logged in a browser

### CODE REVIEW

**Comment by Jivesh-Bisht** [comment]
What  would be the benefit of using it as the phone instead of the browser? is it superior in any ways?

**Comment by Infernite** [comment]
Well I've noticed, one way of their manual detection is, a staff going
through the top leaderboard and checking if user is with [image: image.png]
using a vencord plugin. Although this type of detection is labour intensive
and less used, changing to phone will eliminate the flaw and make the user
seems like they're on a mobile device

**Comment by thejoabo** [comment]
Hello @Infernite 
I understand your reasoning, but I don't like the idea of hard-coding specific values (this was another thing I wanted to change on the bot for a while; there are too many hard-coded values already).

A possible better solution would be to create an array of mobile phone values and then choose one randomly at the start, what do you think ?

Even though I'm not sure how they would be able to detect this, I'm not following their updates on detection and stuff. Also, could you re-send the image from your last reply?

**Comment by Infernite** [comment]
I've experimented with using different arrays and picking random ones but
it's rather going to be the same as my goal is to make discord think that
the user is on a mobile platform. Additionally, using many different
devices could raise security concerns on discord's end(although it's very
unlikely). Perhaps maybe choosing from a small amount of values is a sneaky
approach. So, the detection method goes like this:
Using a vencord plugin - platform indicator. They can see if people are
logged in with a mobile device or on a browser or on a desktop application(
this bypasses idle and dnd). Then, they'd go on to checking accounts that
are logged in a web browser. These are speculations though, I have no
actual proof that this is the exact method they'd take.
Here's an example of how it'd look like on a web browser:
https://imgur.com/a/WgiGYut

**Comment by thejoabo** [comment]
@Infernite , got it. Still, the current commit adds a lot of (already existing) fingerprint to the bot. 

If, as you mentioned, you could create a list of a very limited number of mobile devices (the most generic ones), allowing it to randomly choose one, it would be highly appreciated. This would also address the aforementioned issue of hard-coding.

**Comment by Infernite** [comment]
@thejoabo hello, so I've done the requirements, please let me know if you need anything ^^ I also went ahead and add some more properties for extra safety, feel free to remove it if it doesn't suit the bot.

**Review by thejoabo — APPROVED** [review]
@Infernite, this looks very good to me. These properties can be later reused to compose headers related to x-properties. Great job.

I was reviewing some documentation, and it seems that the only metadata made 'public' in the gateway event is the "os," "browser," and "device" keys. The other ones are optional, and once again, utilizing hard-coded values —especially for versioning-related information— can pose significant problems (I faced issues with their Cloudflare due to specifying too much in requests). But, at this time I don't think it should cause any problems.

Thank you for your contribution.

**Pull request merged**
